# Generated by Django 4.0.2 on 2022-06-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0028_alter_parque_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parque',
            name='foto',
            field=models.ImageField(blank=True, db_column='Foto', null=True, upload_to='images/'),
        ),
    ]
